import {writeFile,mkdir} from 'node:fs/promises';
export const escape = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
export const palettes={dark:{bg:'#0D1117',surface:'#161B22',line:'#30363D',text:'#F0F6FC',muted:'#A0ACBA',cyan:'#39D0FF',violet:'#A371F7'},light:{bg:'#F6F8FA',surface:'#FFFFFF',line:'#D0D7DE',text:'#182230',muted:'#536174',cyan:'#0969A6',violet:'#8250DF'}};
export function svg(w,h,body,p,title){return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-labelledby="title"><title id="title">${escape(title)}</title><defs><pattern id="grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32" fill="none" stroke="${p.line}" stroke-opacity=".25"/></pattern><radialGradient id="glow"><stop stop-color="${p.cyan}" stop-opacity=".14"/><stop offset="1" stop-color="${p.bg}" stop-opacity="0"/></radialGradient></defs><rect x=".5" y=".5" width="${w-1}" height="${h-1}" rx="16" fill="${p.bg}" stroke="${p.line}"/><g font-family="Segoe UI,Arial,sans-serif" fill="${p.text}">${body}</g></svg>\n`;}
export const text=(x,y,s,size=16,color,extra='')=>`<text x="${x}" y="${y}" font-size="${size}" ${color?`fill="${color}"`:''} ${extra}>${escape(s)}</text>`;
export async function asset(name,w,h,render,title){await mkdir('assets/projects',{recursive:true});for(const [theme,p] of Object.entries(palettes)){const path=theme==='dark'?name:name.replace('.svg','-light.svg');await writeFile(`assets/${path}`,svg(w,h,render(p),p,title));}}
export async function staticAssets(){
for(const [theme,p] of Object.entries(palettes))await writeFile(`assets/hero-${theme}.svg`,svg(960,360,`<rect x="1" y="1" width="958" height="358" rx="16" fill="url(#grid)"/><ellipse cx="810" cy="130" rx="300" ry="260" fill="url(#glow)"/>${text(40,48,'SK / ENGINEERING NOTEBOOK',14,p.muted,'letter-spacing="2"')}${text(40,126,'SULTAN',60,p.text,'font-weight="700" letter-spacing="2"')}${text(40,191,'KASSAM',60,p.text,'font-weight="700" letter-spacing="2"')}${text(42,235,'AI INTERFACES / SOFTWARE / WORKFLOWS',18,p.cyan)}${text(42,271,'Connecting intelligent interfaces to practical systems.',18,p.muted)}<path d="M40 300H920" stroke="${p.line}"/>${text(42,330,'PUBLIC WORK / OPEN EXPLORATION',13,p.muted,'letter-spacing="1"')}<g transform="translate(785 155)" fill="none" stroke="${p.cyan}"><circle r="82" stroke-opacity=".15"/><circle r="55" stroke-opacity=".4"/><path d="M-100 0H-36M36 0H100M0-100V-36M0 36V100" stroke-opacity=".5"/><rect x="-22" y="-22" width="44" height="44" rx="9"/><path d="M-9 0H9M0-9V9"/></g>${text(707,330,'sultankassam / github',13,p.muted)}`,p,'Sultan Kassam — AI interfaces, software and workflows'));
await asset('matrix.svg',960,204,p=>text(32,38,'ENGINEERING MATRIX / OBSERVED IN PUBLIC CODE',13,p.muted,'letter-spacing="1"')+[['LANGUAGES','TypeScript / Python','JavaScript / HTML / CSS'],['INTERFACES','React / Next.js','Browser speech APIs'],['APPLICATIONS','Django / ORM','OpenAI API integration']].map((r,i)=>{let x=32+i*310;return text(x,83,r[0],14,p.cyan)+text(x,122,r[1],19)+text(x,153,r[2],17,p.muted)}).join(''),'Technologies observed in Jarvis and AutoMod; not proficiency ratings');
await asset('system-map.svg',960,260,p=>text(32,38,'SYSTEM MAP / TWO DIRECTIONS, ONE ENGINEERING PRACTICE',13,p.muted)+`<path d="M270 130H385M575 130H690" stroke="${p.cyan}" stroke-opacity=".6"/>`+[[32,250,'CONVERSATIONAL','Voice / chat interfaces','Next.js + OpenAI'],[355,250,'PRODUCT SYSTEMS','State / roles / workflows','Software architecture'],[678,250,'OPERATIONAL','Bookings / inventory','Django + Python']].map(([x,w,a,b,c])=>`<rect x="${x}" y="75" width="${w}" height="132" rx="12" fill="${p.surface}" stroke="${p.line}"/>${text(x+20,109,a,15,p.cyan)}${text(x+20,147,b,17)}${text(x+20,179,c,15,p.muted)}`).join('')+text(32,239,'Conceptual domain map; project implementations remain separate.',13,p.muted),'Conceptual map of conversational and operational software domains');
await asset('terminal.svg',960,170,p=>text(32,36,'SESSION / sultankassam',13,p.muted)+text(32,74,'$ focus',17,p.cyan)+text(160,74,'AI interfaces + application workflows',18)+text(32,108,'$ projects',17,p.cyan)+text(160,108,'jarvis / AutoMod',18)+text(32,143,'$ explore',17,p.cyan)+text(160,143,'Build the interface. Connect the workflow.',18,p.muted),'Compact engineering terminal');
await asset('footer.svg',960,66,p=>text(28,39,'SULTAN KASSAM / BUILDING THE NEXT SYSTEM',14,p.muted,'letter-spacing="1"')+`<path d="M780 33h30l7-10 8 20 8-10h90" fill="none" stroke="${p.cyan}" stroke-opacity=".6"/>`,'Sultan Kassam — building the next system');
}
