import {writeFile} from 'node:fs/promises';
import {asset,staticAssets,text} from './design.mjs';
const user='sultankassam';
async function api(path){const headers={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};if(process.env.GITHUB_TOKEN)headers.Authorization=`Bearer ${process.env.GITHUB_TOKEN}`;const r=await fetch(`https://api.github.com/${path}`,{headers,signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`GitHub API HTTP ${r.status}`);return r.json();}
// Public user endpoints only. Never enumerate authenticated/private repositories.
const repos=[];for(let page=1;;page++){const batch=await api(`users/${user}/repos?type=owner&per_page=100&page=${page}`);repos.push(...batch.filter(r=>!r.private&&r.visibility==='public'));if(batch.length<100)break;}
const projects=[{name:'jarvis',title:'JARVIS',purpose:'A voice-enabled conversational interface.',stack:'TypeScript / Next.js / React / OpenAI',detail:'Browser speech, chat memory and file-analysis routes.'},{name:'AutoMod',title:'AUTOMOD',purpose:'Vehicle-service and inventory workflows.',stack:'Python / Django / HTML',detail:'Bookings, parts inventory and mechanic assignment.'}];
const languages={};for(const repo of repos.filter(r=>!r.fork&&r.name!==user)){const data=await api(`repos/${user}/${repo.name}/languages`);for(const [k,v] of Object.entries(data))languages[k]=(languages[k]??0)+v;}
const ranked=Object.entries(languages).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));
// Events API is a bounded recent feed, not an annual contribution count.
const events=[];for(let page=1;page<=3;page++){const batch=await api(`users/${user}/events/public?per_page=100&page=${page}`);events.push(...batch.filter(e=>e.public===true));if(batch.length<100)break;}
const dedup=[...new Map(events.map(e=>[e.id,e])).values()];
await staticAssets();
for(const [i,project] of projects.entries()){const r=repos.find(r=>r.name===project.name);if(!r)throw new Error('Showcase project is no longer public');await asset(`projects/project-0${i+1}.svg`,960,208,p=>text(32,35,`0${i+1} / PUBLIC PROTOTYPE`,13,p.muted)+text(32,82,project.title,32,p.text,'font-weight="700"')+text(32,116,project.purpose,22)+text(32,148,project.detail,17,p.muted)+text(32,183,project.stack,16,p.cyan)+text(705,183,`PUSH / ${r.pushed_at.slice(0,10)}`,13,p.muted),`${project.title}: ${project.purpose} ${project.stack}`);}
const original=repos.filter(r=>!r.fork&&r.name!==user);const latest=original.map(r=>r.pushed_at).sort().at(-1)?.slice(0,10)??'No public pushes';
await asset('stats.svg',960,180,p=>text(32,35,'ENGINEERING SIGNAL / PUBLIC GITHUB API',13,p.muted)+text(32,89,String(original.length),38,p.text,'font-weight="700"')+text(32,122,'Original project repositories',16,p.muted)+text(360,81,ranked.slice(0,2).map(x=>x[0]).join(' / ')||'No language data',23)+text(360,122,'Leading languages by source bytes',16,p.muted)+text(710,81,latest,23)+text(710,122,'Latest project push',16,p.muted)+text(32,158,'Excludes forks and this profile repository. Source bytes are not proficiency scores.',13,p.muted),'Public original repository count, leading languages and latest project push');
const now=new Date(),days=[];for(let i=27;i>=0;i--){const d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()-i)).toISOString().slice(0,10);days.push({date:d,count:dedup.filter(e=>e.created_at.slice(0,10)===d).length});}const max=Math.max(1,...days.map(d=>d.count));
await asset('activity.svg',960,184,p=>text(32,34,'ACTIVITY PULSE / RECENT PUBLIC EVENTS',13,p.muted)+days.map((d,i)=>{const h=d.count?Math.max(5,d.count/max*65):2;return `<rect x="${32+i*32}" y="${118-h}" width="19" height="${h}" rx="3" fill="${d.count?p.cyan:p.line}"/>`;}).join('')+text(32,145,days[0].date,13,p.muted)+text(804,145,days.at(-1).date,13,p.muted)+text(32,169,'28-day UTC window. Bounded GitHub events feed; not commits or total contributions.',13,p.muted),'28-day pulse of returned public GitHub events; bounded feed, not contribution totals');
// Persist a minimal public snapshot only after all requests succeed.
await writeFile('docs/public-snapshot.json',JSON.stringify({source:'GitHub public REST endpoints',repositories:original.map(r=>({name:r.name,language:r.language,stars:r.stargazers_count,forks:r.forks_count,pushedAt:r.pushed_at})),languages:ranked,activity:days},null,2)+'\n');
console.log('Generated profile assets from public data.');
