import {writeFile} from 'node:fs/promises';
import {asset,staticAssets,text} from './design.mjs';
const user='sultankassam';
async function api(path){const headers={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};if(process.env.GITHUB_TOKEN)headers.Authorization=`Bearer ${process.env.GITHUB_TOKEN}`;const r=await fetch(`https://api.github.com/${path}`,{headers,signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`GitHub API HTTP ${r.status}`);return r.json();}
// Public user endpoints only. Never enumerate authenticated/private repositories.
const repos=[];for(let page=1;;page++){const batch=await api(`users/${user}/repos?type=owner&per_page=100&page=${page}`);repos.push(...batch.filter(r=>!r.private&&r.visibility==='public'));if(batch.length<100)break;}
const projects=[{name:'jarvis',title:'JARVIS',purpose:'A voice-enabled conversational interface.',stack:'TypeScript / Next.js / React / OpenAI',detail:'Browser speech, chat memory and file-analysis routes.'},{name:'AutoMod',title:'AUTOMOD',purpose:'Vehicle-service and inventory workflows.',stack:'Python / Django / HTML',detail:'Bookings, parts inventory and mechanic assignment.'}];
const languages={};for(const repo of repos.filter(r=>!r.fork&&r.name!==user)){const data=await api(`repos/${user}/${repo.name}/languages`);for(const [k,v] of Object.entries(data))languages[k]=(languages[k]??0)+v;}
const ranked=Object.entries(languages).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));
// Events API is a bounded recent feed, not an annual contribution count.
const events=[];for(let page=1;page<=3;page++){const batch=await api(`users/${user}/events/public?per_page=100&page=${page}`);events.push(...batch.filter(e=>e.public===true));if(batch.length<100)break;}
const dedup=[...new Map(events.map(e=>[e.id,e])).values()];
await staticAssets();
for(const [i,project] of projects.entries()){const r=repos.find(r=>r.name===project.name);if(!r)throw new Error('Showcase project is no longer public');await asset(`projects/project-0${i+1}.svg`,960,208,p=>text(32,35,`0${i+1} / PUBLIC PROTOTYPE`,13,p.muted)+text(32,82,project.title,32,p.text,'font-weight="700"')+text(32,116,project.purpose,22)+text(32,148,project.detail,17,p.muted)+text(32,183,project.stack,16,p.cyan)+text(705,183,`PUSH / ${r.pushed_at.slice(0,10)}`,13,p.muted),`${project.title}: ${project.purpose} ${project.stack}`);}
const original=repos.filter(r=>!r.fork&&r.name!==user);const latest=original.map(r=>r.pushed_at).sort().at(-1)?.slice(0,10)??'No public pushes';
await asset('stats.svg',960,180,p=>text(32,35,'ENGINEERING SIGNAL / PUBLIC GITHUB API',13,p.muted)+text(32,89,String(original.length),38,p.text,'font-weight="700"')+text(32,122,'Original project repositories',16,p.muted)+text(360,81,ranked.slice(0,2).map(x=>x[0]).join(' / ')||'No language data',23)+text(360,122,'Leading languages by source bytes',16,p.muted)+text(710,81,latest,23)+text(710,122,'Latest project push',16,p.muted)+text(32,158,'Excludes forks and this profile repository. Source bytes are not proficiency scores.',13,p.muted),'Public original repository count, leading languages and latest project push');
const now=new Date(),days=[];for(let i=27;i>=0;i--){const d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()-i)).toISOString().slice(0,10);days.push({date:d,count:dedup.filter(e=>e.created_at.slice(0,10)===d).length});}const max=Math.max(1,...days.map(d=>d.count));
await asset('activity.svg',960,184,p=>text(32,34,'ACTIVITY PULSE / RECENT PUBLIC EVENTS',13,p.muted)+days.map((d,i)=>{const h=d.count?Math.max(5,d.count/max*65):2;return `<rect x="${32+i*32}" y="${118-h}" width="19" height="${h}" rx="3" fill="${d.count?p.cyan:p.line}"/>`;}).join('')+text(32,145,days[0].date,13,p.muted)+text(804,145,days.at(-1).date,13,p.muted)+text(32,169,'28-day UTC window. Bounded GitHub events feed; not commits or total contributions.',13,p.muted),'28-day pulse of returned public GitHub events; bounded feed, not contribution totals');
// Persist a minimal public snapshot only after all requests succeed.
await writeFile('docs/public-snapshot.json',JSON.stringify({source:'GitHub public REST endpoints',repositories:original.map(r=>({name:r.name,language:r.language,stars:r.stargazers_count,forks:r.forks_count,pushedAt:r.pushed_at})),languages:ranked,activity:days},null,2)+'\n');
console.log('Generated profile assets from public data.');
// Narrow-screen assets use larger type and vertical layouts rather than scaling desktop columns.
await asset('hero-mobile.svg',480,330,p=>text(24,36,'SK / ENGINEERING NOTEBOOK',13,p.muted)+text(24,102,'SULTAN',47,p.text,'font-weight="700"')+text(24,154,'KASSAM',47,p.text,'font-weight="700"')+text(24,200,'AI INTERFACES / SOFTWARE',18,p.cyan)+text(24,233,'Connecting intelligent interfaces',19)+text(24,262,'to practical systems.',19)+text(24,307,'sultankassam / github',14,p.muted),'Sultan Kassam — AI interfaces and software');
for(const [i,project] of projects.entries())await asset(`projects/project-0${i+1}-mobile.svg`,480,248,p=>text(24,33,`0${i+1} / PUBLIC PROTOTYPE`,14,p.muted)+text(24,81,project.title,34,p.text,'font-weight="700"')+text(24,119,i===0?'Voice-enabled AI conversation.':'Vehicle-service workflows.',22)+text(24,155,i===0?'Browser speech / chat / file analysis':'Bookings / inventory / assignment',17,p.muted)+text(24,192,i===0?'TypeScript / Next.js / React':'Python / Django / HTML',18,p.cyan)+text(24,228,`LATEST PUSH / ${repos.find(r=>r.name===project.name).pushed_at.slice(0,10)}`,14,p.muted),project.purpose);
await asset('matrix-mobile.svg',480,310,p=>text(24,34,'ENGINEERING MATRIX',15,p.muted)+[['LANGUAGES','TypeScript / Python / JavaScript','HTML / CSS'],['INTERFACES','React / Next.js / browser speech','OpenAI API integration'],['APPLICATIONS','Django / ORM','Verified in public code']].map((r,i)=>text(24,76+i*80,r[0],14,p.cyan)+text(24,104+i*80,r[1],19)+text(24,129+i*80,r[2],16,p.muted)).join(''),'Engineering matrix of technologies in public code');
await asset('system-map-mobile.svg',480,365,p=>text(24,34,'SYSTEM MAP / CONCEPTUAL DOMAINS',14,p.muted)+[['CONVERSATIONAL','Voice / chat — Next.js + OpenAI'],['PRODUCT SYSTEMS','State / roles / workflows'],['OPERATIONAL','Bookings / inventory — Django']].map((r,i)=>`<rect x="24" y="${55+i*96}" width="432" height="76" rx="12" fill="${p.surface}" stroke="${p.line}"/>${text(42,82+i*96,r[0],15,p.cyan)}${text(42,110+i*96,r[1],18)}${i<2?`<path d="M240 ${131+i*96}v20" stroke="${p.cyan}"/>`:''}`).join('')+text(24,347,'Separate projects; shared engineering domains.',16,p.muted),'Conceptual domains; separate project implementations');
await asset('stats-mobile.svg',480,287,p=>text(24,34,'ENGINEERING SIGNAL / PUBLIC API',14,p.muted)+text(24,83,`${original.length} original project repositories`,25)+text(24,118,'Excludes forks and the profile repository.',16,p.muted)+text(24,166,ranked.slice(0,2).map(x=>x[0]).join(' / '),25)+text(24,196,'Leading languages by source bytes',16,p.muted)+text(24,240,latest,25)+text(24,267,'Latest project push',16,p.muted),'Public repository count, languages and latest project push');
await asset('activity-mobile.svg',480,185,p=>text(24,32,'ACTIVITY PULSE / PUBLIC EVENTS',14,p.muted)+days.map((d,i)=>{const h=d.count?Math.max(4,d.count/max*60):2;return `<rect x="${24+i*15.4}" y="${105-h}" width="9" height="${h}" rx="2" fill="${d.count?p.cyan:p.line}"/>`;}).join('')+text(24,133,days[0].date,14,p.muted)+text(340,133,days.at(-1).date,14,p.muted)+text(24,158,'28-day UTC window / bounded public feed',15,p.muted)+text(24,179,'Events, not commit or contribution totals.',15,p.muted),'28-day bounded public event pulse');
await asset('terminal-mobile.svg',480,200,p=>text(24,34,'SESSION / sultankassam',14,p.muted)+text(24,77,'$ focus',18,p.cyan)+text(24,105,'AI interfaces + application workflows',19)+text(24,147,'$ projects',18,p.cyan)+text(24,176,'jarvis / AutoMod',20),'Engineering focus and public projects');
await asset('footer-mobile.svg',480,82,p=>text(24,34,'SULTAN KASSAM',18,p.muted)+text(24,62,'BUILDING THE NEXT SYSTEM',15,p.cyan),'Sultan Kassam — building the next system');
